name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:    
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Copy docker-compose.yml via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "docker-compose.production.yml"
        target: "kittygram"
    - name: Executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          set -e
          cd kittygram
          cat > .env << EOF
          POSTGRES_DB=kittygram
          POSTGRES_USER=kittygram_user
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          DB_NAME=kittygram
          DB_HOST=db
          DB_PORT=5432
          DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}"
          ALLOWED_HOSTS=157.22.196.19
          EOF
          docker-compose -f docker-compose.production.yml pull
          docker-compose -f docker-compose.production.yml down
          docker-compose -f docker-compose.production.yml up -d
          sleep 5
          docker-compose -f docker-compose.production.yml exec -T backend python manage.py migrate
          docker-compose -f docker-compose.production.yml exec -T backend python manage.py collectstatic --noinput
          docker-compose -f docker-compose.production.yml exec -T backend cp -r /app/collected_static/. /static/static/