name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build_gateway_and_push_to_docker_hub:
    name: Push gateway Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./nginx/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kittygram_gateway:latest    
  deploy:
    runs-on: ubuntu-latest
    needs: build_gateway_and_push_to_docker_hub
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Copy docker-compose.yml via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "docker-compose.production.yml"
        target: "kittygram"
    - name: Executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          set -e
          cd kittygram
          cat > .env << EOF
          POSTGRES_DB=kittygram
          POSTGRES_USER=kittygram_user
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          DB_NAME=kittygram
          DB_HOST=db
          DB_PORT=5432
          DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}"
          ALLOWED_HOSTS=157.22.196.19
          EOF
          docker-compose -f docker-compose.production.yml pull
          docker-compose -f docker-compose.production.yml down
          docker-compose -f docker-compose.production.yml up -d
          sleep 5
          docker-compose -f docker-compose.production.yml exec -T backend python manage.py migrate
          echo "migrate"
          docker-compose -f docker-compose.production.yml exec -T backend python manage.py collectstatic --noinput
          echo "collect"
          docker-compose -f docker-compose.production.yml exec -T backend cp -r /app/collected_static/. /app/static/ 
          echo "static"
